### PR TITLE
optimised pow function in radix.cpp

### PR DESCRIPTION
**Pull request by jvmolu**
Anmol Singhal
11940140
anmolsinghal@iitbhilai.ac.in

### CODE REVIEW

**Comment by shashwatj07** [comment]
@jvmolu please rebase and resolve conflict

**Comment by jvmolu** [comment]
@shashwatj07 done

**Review by shashwatj07 — APPROVED** [review]
looks good

**Comment by shashwatj07** [comment]
@jvmolu amend your commit message appropriately and force push

**Comment by shashwatj07** [comment]
@yatendra1999 ping

**Review by yatendra1999 — APPROVED** [review]
LGTM

**Pull request merged**
